

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  maven_version:
    uses: sfuhrm/github_workflows/.github/workflows/maven-expression.yml@main
    with:
      java_version: 22
      expression: project.version
  call-workflow-passing-data:
    needs: maven_version
    uses: sfuhrm/github_workflows/.github/workflows/maven.yml@main
    with:
      java_version: "[\"22\", \"25\"]"
      artifact_name: build
      artifact_path: target/magick2imageio-${{ needs.maven_version.outputs.expression_value }}.jar
      test_artifact_name: tests
      test_artifact_path: target/surefire-reports
      prebuild_script: sudo apt install -y libmagickwand-6.q16-7t64
